djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', authentication_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout', authentication_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.profile_page, name='profile'),
]


urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/urls.py
from . import views
from django.urls import path


app_name = 'food'
urlpatterns = [
    # /food/
    path('', views.IndexClassView.as_view(), name='index'),
    # path('', views.index, name='index'),                         for def based view
    # /food/1
    path('<int:pk>/', views.FoodDetail.as_view(), name='detail'),
    # path('<int:item_id>/', views.detail, name='detail'),         for def based view
    path('item/', views.item, name='item'),
    # add item
    path('add', views.CreateItem.as_view(), name='create_item'),
    # path('add', views.create_item, name='create_item'),          for def based view
    # edit
    path('update/<int:id>/', views.update_item, name='update_item'),
    # delete
    path('delete/<int:id>/', views.delete_item, name='delete_item')
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg', upload_to='profile_picture')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

food/forms.py
from django import forms
from .models import Item


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name', 'item_desc', 'item_price', 'item_image']

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

food/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import ItemForm
from .models import Item
from django.contrib.auth.decorators import login_required
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
# Create your views here.


def index(request):
    item_list = Item.objects.all()
    context = {
        'item_list': item_list,
    }
    return render(request, 'food/index.html', context)


class IndexClassView(ListView):
    model = Item
    template_name = 'food/index.html'
    context_object_name = 'item_list'


def item(request):
    return HttpResponse('this is an item view')


def detail(request, item_id):
    item = Item.objects.get(pk=item_id)
    context = {
        'item': item,
    }

    return render(request, 'food/detail.html', context)


class FoodDetail(DetailView):
    model = Item
    template_name = 'food/detail.html'


# @login_required
# def create_item(request):
#     form = ItemForm(request.POST or None)
#
#     if form.is_valid():
#         form.save()
#         return redirect('food:index')
#
#     return render(request, 'food/item-form.html', {'form': form})


# class based:
# @login_required
class CreateItem(CreateView):
    model = Item
    fields = ['item_name', 'item_desc', 'item_price', 'item_image']
    template_name = 'food/item-form.html'

    def form_valid(self, form):
        form.instance.user_name = self.request.user

        return super().form_valid(form)


@login_required
def update_item(request, id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request, 'food/item-form.html', {'form': form, 'item': item})


@login_required
def delete_item(request, id):
    item = Item.objects.get(id=id)

    if request.method == 'POST':
        item.delete()
        return redirect('food:index')

    return render(request, 'food/item-delete.html', {'item': item})

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import RegisterForm
# Create your views here.


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Welcome {username}.')
            return redirect('login')
    else:
        form = RegisterForm()
    return render(request, 'users/register.html', {'form': form})


@login_required
def profile_page(request):
    return render(request, 'users/profile.html')

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous"></script>
    <title>Food App</title>
</head>
<body>

<nav class="navbar navbar-light" style="background-color: mediumorchid; padding-left: 20px">
    <a href="{% url 'food:index' %}" class="navbar-brand"> Food App </a>

    <div class="navbar">
        {% if user.is_authenticated %}
            <a class="nav-item nav-link" style="padding-right: 30px" href="{% url 'food:create_item' %}"> Add Item </a>
            <a class="nav-item nav-link" style="padding-right: 30px" href="{% url 'profile' %}">Profile</a>
            <a class="nav-item nav-link" style="padding-right: 30px" href="{% url 'logout' %}">Log Out</a>
        {% else %}
            <a class="nav-item nav-link" style="padding-right: 30px" href="{% url 'login' %}">Log in</a>
            <a class="nav-item nav-link" style="padding-right: 30px" href="{% url 'register' %}">Sign Up</a>
        {% endif %}
    </div>
</nav>

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}


{% block body %}
{% endblock %}

</body>
</html>

food/templates/food/detail.html
{% extends 'food/base.html' %}

{% block body %}

    <div class="container">
        <div class="row>">
            <div class="col-md-6">

                <img src="{{ item.item_image }}" height="100px" class="card"/>

            </div>

            <div class="col-md-6">
                <h1>{{ object.item_name }}</h1>
                <h2>{{ object.item_desc }}</h2>
                <h3>${{ object.item_price }}</h3>
                <h6>{{ object.user_name }}</h6>
                {% if user.is_authenticated %}
                    <a href="{% url 'food:delete_item' item.id %}">Delete</a>
                {% endif %}
            </div>
        </div>
    </div>




{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %}

{% block body %}

    {% for item in item_list %}
        <div class="row">
            <div class="col-md-3 offset-md-2">
                <img class="card" height="150px" src="{{ item.item_image }}"/>
            </div>
            <div class="col-md-4">
                <h3>{{ item.item_name }}</h3>
                <h5>{{ item.item_desc }}</h5>
                <h6>${{ item.item_price }}</h6>
            </div>
            <div class="col-md-2">
                <a href="{% url 'food:detail' item.id %}" class="btn btn-success"> Details </a>
                {% if user.is_authenticated %}
                <a href="{% url 'food:update_item' item.id %}" class="btn btn-success"> Edit Item </a>
                {% endif %}
            </div>
        </div>
    {% endfor %}

{% endblock %}

this is the old code
{#{% block body %}#}
{#{% for item in item_list %}#}
{##}
{#    <ul>#}
{#        <li>#}
{#            <a href="{% url 'food:detail' item.id %}">{{ item.id }} -- {{ item.item_name }}</a>#}
{#        </li>#}
{#    </ul>#}
{##}
{#{% endfor %}#}
{#{% endblock %}#}

food/templates/food/item-delete.html
<form method="POSt">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{ item.item_name }}?</h2>
    <button type="submit">Confirm</button>
</form>

food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4" style="padding: 30px">
                <div class="card">
                    <div class="card-header text-white" style="background-color: cornflowerblue">
                        <div class="card-title">
                            Add Item
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group" style="padding: 10px">
                                    {{ field.name }}
                                    {{ field }}
                                </div>
                            {% endfor %}
                            <button class="offset-md-5 text-white" style="background-color: cornflowerblue; border-radius: 5px" type="submit">Add</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

users/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous"></script>
    <title>Food App</title>
</head>
<body>

<nav class="navbar navbar-light" style="background-color: mediumorchid; padding-left: 20px">
    <a href="{% url 'food:index' %}" class="navbar-brand"> Food App </a>

    <div class="navbar">
        <a class="nav-item nav-link" style="padding-right: 30px" href="{% url 'register' %}"> Sign Up </a>
        <a class="nav-item nav-link" style="padding-right: 30px" href="{% url 'login' %}"> Log In </a>
        <a class="nav-item nav-link" style="padding-right: 30px" href="{% url 'logout' %}"> Log Out </a>
    </div>
</nav>

{% block body %}
{% endblock %}

</body>
</html>

users/templates/users/baseloginout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous"></script>
    <title>Food App</title>
</head>
<body>

<nav class="navbar navbar-light" style="background-color: mediumorchid; padding-left: 20px">
    <a href="{% url 'food:index' %}" class="navbar-brand"> Food App </a>

    <div class="navbar">
        {% if user.is_authenticated %}
            <a class="nav-item nav-link" style="padding-right: 30px" href="{% url 'profile' %}">Profile</a>
            <a class="nav-item nav-link" style="padding-right: 30px" href="{% url 'logout' %}">Log Out</a>
        {% else %}
            <a class="nav-item nav-link" style="padding-right: 30px" href="{% url 'login' %}">Log in</a>
            <a class="nav-item nav-link" style="padding-right: 30px" href="{% url 'register' %}">Sign Up</a>
        {% endif %}
    </div>
</nav>

{% block body %}
{% endblock %}

</body>
</html>

users/templates/users/login.html
{% extends 'users/baseloginout.html' %}

{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4" style="padding: 30px">
                <div class="card">
                    <div class="card-header text-white" style="background-color: darkslateblue">
                        <div class="card-title">
                            Login
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group" style="padding: 10px">
                                    {{ field.name }}
                                    {{ field }}
                                </div>
                            {% endfor %}
                            <button class="offset-md-5 text-white" style="background-color: darkslateblue; border-radius: 5px" type="submit">Login</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

users/templates/users/logout.html
<h2>you have been logged out</h2>

users/templates/users/profile.html
{% extends 'food/base.html' %}

{% block body %}
    <h1>{{ user.username }}</h1>
    <img width="100px" height="100px" src="{{ user.profile.image.url }}">
{% endblock %}

users/templates/users/register.html
{% extends 'users/baseloginout.html' %}

{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4" style="padding: 30px">
                <div class="card">
                    <div class="card-header text-white" style="background-color: darkslateblue">
                        <div class="card-title">
                            Register
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group" style="padding: 10px">
                                    {{ field.name }}
                                        <br>
                                    {{ field }}
                                </div>
                            {% endfor %}
                            <button class="offset-md-5 text-white"
                                    style="background-color: darkslateblue; border-radius: 5px" type="submit">Signup
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}